// swift-tools-version: 6.3

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Display",
    platforms: [
        .iOS("26.0"),
        .macCatalyst("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Display",
            targets: ["App"],
            bundleIdentifier: "tools.ars.display",
            displayVersion: "1.0",
            appIcon: .placeholder(icon: .tv),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ],
            capabilities: [
                .camera(purposeString: "Audio Input")
                .microphone(purposeString: "Video Input"),
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "App",
            path: "Sources"
        )
    ],
    swiftLanguageModes: [.version("6")]
)
